### ISSUE TITLE
Named Arguments Cause Unexpected Argument Error

### ISSUE THREAD

**Issue by CarrotDLaw** [taylorh140/typst-pintora#4]
Currently, the code 

```typ
#show raw.where(lang: "pintora"): it => pintorita.render(it.text, font: "Victor Mono")
```
 
 causes the following error
 
 ```
error: unexpected argument: font
   ┌─ @preview/pintorita:0.1.2/pintorita.typ:20:41
   │
20 │   image.decode(svg-output, ..args.pos(), ..named-args)
   │                                          ^^^^^^^^^^^^
```

.

I found that in `pintorita.typ`, the named arguments except `factor` are not removed before passed into `image.decode()`, which is inconsistent with the documentation.

**Comment by taylorh140** [comment]
Thanks for the issue, 
It seems like the arguments need to be cleaned a bit more on the way down. 

Do you need this resolved soon?

**Comment by fabriceci** [comment]
I'm new to Typst, I wanted to change the theme (I don't want a colored background) and I got the same error. I thought it was a syntax problem on my side, in fact I only have the factor parameter that I can pass like CarrotDLaw.

```
Unexpected argument: style
```

**Comment by taylorh140** [comment]
It's a real problem; I haven't got a chance quite yet to fix it. Ill shoot for the new year.
